### ISSUE TITLE
[FEATURE] Integration with automated-jb2a-animations

### ISSUE THREAD

**Issue by johnnolan** [johnnolan/wild-magic-surge-5e#150]
**Describe the new feature**
When a surge is detected, can I optionally trigger an effect via [automated-jb2a-animations](https://github.com/otigon/automated-jb2a-animations).

**Expected behavior**
On a surge, trigger an animation using the Hook provided in [automated-jb2a-animations](https://github.com/otigon/automated-jb2a-animations).

**Additional Information**

* Can the user customise the animation to run?

To use the AA call from a macro, use:
AutoAnimations.playAnimation(sourceToken, targets, item)

where sourceToken is the originating token, Targets is an Array from the users targets, and Item is the item being used that has been configured with the AA settings tab

**Comment by nirurin** [comment]
"Wild Magic Surge 5e: Play animation on surge is enabled in settings but the JB2A module is not active/installed. Disable the play animation in settings or install and enable JB2A."

I have the latest JB2a module manifest installed, and it's active (it's even firing a JB2a animation for the spell I cast to test wild magic surged), but the above message is still popping up?
