### ISSUE TITLE
Suggestion: Add option to make target roll depended on the Spell level.

### ISSUE THREAD

**Issue by Jackolas126** [johnnolan/wild-magic-surge-5e#24]
It would be cool to have an option to make the target roll instead of 1 (or an other fixed number) be depended on the spell level that is cast (or maybe an entire other formula).
In my current campaign I run I have a custom rule: how more powerfull a spell is the more likely its gone trigger wild magic
So a lvl 1 spell only triggers wild magic if a 1 is rolled on the d20
a lvl 4 spell triggers if a 4 or lower is rolled
and a lvl 9 triggers if a 9 or lower is rolled

it would be nice to imitate that with this module

**Comment by johnnolan** [comment]
Really like this idea... may steal it for my games. Leave it with me and will get on it when I can, thanks for the suggestion
