### ISSUE TITLE
[BUG] With Maco without <p>

### ISSUE THREAD

**Issue by CaosFR** [johnnolan/wild-magic-surge-5e#285]
**Describe the bug**
HI and thanks for your module. I have a strange error with your module when I use a macro for equip/unequip a item. If I add `<p> [...> </p>` to `chatMessage(actor.name + ' [...] '</i>');` it's ok. I dont understand.

```
/**
 * D&D5e biased, paths may be wrong in other systems!
 * Equips/unequips an item. Make sure you change the variables at the top (as required).
 * This script will also error check to make sure items exist and tokens are select. 
 * Chat can be set as desired.
 * Author: Zapgun, Freeze#2689 (fix for v9)
 */

const itemName = 'Gourdin Magique'; // <--- Objet qui ne sera equiper
const itemName2 = 'Gourdin'; // <--- Objet qui ne sera plus equiper
const sendToChat = true; // <--- Affichage dans le chat
let toggleResult = false; // Ne pas afficher des infos de la macro

if (!actor) 
{
	ui.notifications.warn('Vous devez sélectionner un token pour utiliser cette macro!');
} 
else 
{

	const myItem = actor.items.getName(itemName);
	const myItem2 = actor.items.getName(itemName2);
	if (myItem) 
        {
		let item = actor.items.get(myItem.id);
		let attr = "data.equipped";
		let equipped = getProperty(item.data, attr);
		let item2 = actor.items.get(myItem2.id);
		if (sendToChat) 
                {
			if (!equipped)
                        {
				chatMessage(actor.name + ' <b>insufle la magie</b> dans son <i>' + ' ' + itemName + '</i>');
			} 
                        else 
                        {
				chatMessage(actor.name + ' <b>libère la magie</b> de son <i>' + ' ' + itemName + '</i>');
			}
		}
		item.update({ [attr]: !getProperty(item.data, attr) });
		item2.update({ [attr]: !getProperty(item2.data, attr) });
	} 
        else 
        {
		ui.notifications.warn("Pas d'objet nommé '" + itemName + "' trouvé dans la fiche!");
	}
}

function chatMessage(messageContent) 
{
	// Creation du message
	if (messageContent !== '') 
        {
		let chatData = 
                {
			user: game.user.id,
			speaker: ChatMessage.getSpeaker(),
			content: messageContent,
		};
		ChatMessage.create(chatData, {});
	}
}
```

**What version of FoundryVTT are you using?**
0.9.X latest

**To Reproduce**
1. Launch a macro
2. Open console F12
3. See error

**Expected behavior**
No error in console

**Screenshots**
![image](https://user-images.githubusercontent.com/37581932/191364458-08f384cf-f0a8-4da9-81d6-2025ab9c1729.png)

**Comment by johnnolan** [comment]
Hi, so sorry but that looks like an older V9 version of module which is no longer supported. I am away for a few days at the minute but will see if there is anything I can suggest when I get back for you, sorry!

**Comment by CaosFR** [comment]
Dont worry, it's just a warning. As I say I have add "<p> </p>" in all output to chat and it's ok. I just dont understand why.

**Comment by johnnolan** [comment]
Ah okay, no problem, the older versions of the module used to read the chatmesssages and could cause those sort of issues, glad its still workable for you. This should go away when you are ready to upgrade.

Shout if you need any other help
