### ISSUE TITLE
[BUG] Impossible: Track incremental and descending die wild magic surge count on token

### ISSUE THREAD

**Issue by Jefferydo** [johnnolan/wild-magic-surge-5e#310]
The github documentation page [Track Surge Token](https://github.com/johnnolan/wild-magic-surge-5e/blob/main/docs/TRACK_SURGE_TOKEN.md)  suggests setting a specific value in the token's Resources > Bar 2 Attribute field:

> To view your count on your token, set the following resource resources.wmsurgeincrement or resources.wmsurgedescending to be tracked.

However, the attribute field only permits values from a drop-down list. There's no option to edit the field to enter the custom values.

**Comment by johnnolan** [comment]
Hi, thanks for raising, the two options should be selectable from that drop down, no need to manually type in the value.

If they aren't showing, it could be that the character hasn't caused the module to run a check yet and so hasn't set the default value yet.

Could you set the module to use either of those methods for wild magic surges.
Then cast a spell level 1 or higher
Refresh the browser
Try again

If that doesn't make it show up then could you export your character please and send me the json file? (right click the actor in the side bar and choose export data)

![image](https://user-images.githubusercontent.com/5390820/193424029-6001b81f-7dc2-4aa3-8a9c-01dcacae3d7a.png)

If it does work then I will look to ways of adding that property somehow when the module is installed for future users.

**Comment by johnnolan** [comment]
Latest release `3.8.5` will setup those flags on load so you wont have to do the above steps to show it on first use. Let me know if you have any more issues

**Comment by Jefferydo** [comment]
Alas, I'm running v 9 and your update requires 10.

I followed your steps while logged in as GM. I chose descending dice and kept casting until I triggered a surge. I refreshed Foundry. Neither resource showed up in the list of options. Please find the character sheet attached. I changed the file extension from .json to .txt in order to attach it.

Incidentally, I found a few more bugs:

I enabled DF Manual Rolls, entered a 1 and it didn't trigger a surge.

When I did trigger a surge using descending dice, the chat message prompted to roll 1d100 instead of rolling on the table. I have both "Automate Wild Magic Surge" and "Auto Roll Table" set.

Minor tweak: In the documentation for character set up, you refer to Wild Magic Surge and Tides of Chaos as "feats," but they're both class features:

> Ensure under the features tab on your character sheet that you have a Feat called Wild Magic Surge.

> Ensure under the features tab on your character sheet that you have a Feat call Tides of Chaos.

On a different topic entirely, I'm hoping to create some of the Path of Wild Magic effects, e.g., 1d12 necrotic damage within 30' to targets of your choosing plus heal 1d12. I don't know what can be achieved via the form interface with short text fragments vs what needs a macro. I haven't studied any of it yet and  don't know where to begin.. Can I bother you to point me to a beginner's tutorial? Maybe list some of the keywords I should be using in searches?

[fvtt-Actor-zangros-zankrhethfaeries.txt](https://github.com/johnnolan/wild-magic-surge-5e/files/9691242/fvtt-Actor-zangros-zankrhethfaeries.txt)

**Comment by johnnolan** [comment]
Ah so sorry, the animations, resources and DF Manual Rolls are all v10 compatibility. V10 I was able to rewrite the module to better connect with rolls and animations that just weren't possible in v9.

In the v10 version you can also create your own animations via a macro and sequencer.

Unfortunately for now until you upgrade, you won't get those features out of the v9 version :(

dnd5e helpers module has a wild magic surge function that may help for now if you can't get this working on v9 until you get to a point to upgrade.

On the docs, good catch and thanks for letting me know, will update from Feat!

WIll have a think on the path of wild magic effects for you and get back, there has to be a nice way
