### ISSUE TITLE
[FEATURE] Integrate with DF Manual Rolls

### ISSUE THREAD

**Issue by Jefferydo** [johnnolan/wild-magic-surge-5e#312]
I enabled DF Manual Rolls, entered a 1 and it didn't trigger a surge.

I left some feedback on a couple of other issues on the bug re Track incremental and descending die wild magic surge count on token

**Comment by johnnolan** [comment]
Unfortunately this won't work on v9 but for when you upgrade to v10 I will double check this functionality for you

**Comment by johnnolan** [comment]
Confirmed when using DF Manual Rolls that entering a `1` in the popup returns a roll of  `1` and triggers a wild magic surge in V10.
