### ISSUE TITLE
Feature request: Display Wild Magic Surge Threshold

### ISSUE THREAD

**Issue by AdamSturge** [johnnolan/wild-magic-surge-5e#34]
I've been doing pretty much exactly what the incremental option for wild magic surge does by hand so finding this module has been great. The one thing it doesn't do that I did is track the current threshold for a surge in a resource bar (similar to HP except with a hard coded 1-20 max). It never resets until a wild magic surge is triggered. Would it be possible to add a option to track the threshold in this way. Specific a resource bar number/name to tie it to? It's useful for the players to know how likely they are to trigger a surge from a strategic sense. And it also has some fun roleplay/hype building opportunities.

**Comment by johnnolan** [comment]
Hey man, thanks for the feedback!

Ooh I love this idea, have never built in a status bar of some sort yet. Let me have a think on some designs on how this could look without cluttering the UI and I will give it a go. Thanks for the suggestion!

Just for my notes and feel free to comment on your preferred way

- Status bar under token
- Status bar on Character sheet
- Notification on Chat Message with chances
- status bar at some point on the screen for that user, like just above the macro bar

**Comment by AdamSturge** [comment]
The way I do it in Foundry right now is just assign it to a resource bar. Which already has controls for where it's displayed and who can see it. So for my wild mage player he ends up with his HP and wild magic counter underneath his token
