### ISSUE TITLE
Change Die Size on No Surge [Enhancement]

### ISSUE THREAD

**Issue by ravingdragoon** [johnnolan/wild-magic-surge-5e#36]
I use the variant where you change the die size to the next size down until a one is rolled. Is there a way you could implement this in this module?

Example: PC rolls a d20 and gets a 5, next spell they roll a d12 and roll an 11, next spell they roll a d10 and roll a 4, next spell they roll a d8 and roll a2, next spell a d6 and a 5, next spell a d4 and a 2, then continue with a d4 until a 1 is rolled. Die size would always reset to a d20 after a 1 is rolled, no matter what the die size is currently.

**Comment by johnnolan** [comment]
Hi, that can definitely be done, will add it to my list and update this ticket as I get through it for you!

I recently added a notification to chat for the incremental version as well as making it visible on the token (See the readme for what it looks and behaves like). Would you expect any feedback as to what is being rolled in the chat window or just have it blind to the players and say when it is a surge?

**Comment by ravingdragoon** [comment]
You are awesome! Thanks so much for this update!
