### ISSUE TITLE
flag for surge_increment_resource is missing

### ISSUE THREAD

**Issue by AdamSturge** [johnnolan/wild-magic-surge-5e#39]
The how to page mentions this field when setting up a resource to track the wild magic surge incremental counter. However I do not see that option
![Untitled](https://user-images.githubusercontent.com/3497703/135930226-6dbc2604-7e43-4a32-a716-7d6f5cd93642.png)

**Comment by johnnolan** [comment]
Hi, the entry may be at the top in the Attribute Bars section. Can you check there? Also you may need to cast a spell first for it to appear. If thats true I wil add a bug fix in later to get it added on start up

![image](https://user-images.githubusercontent.com/5390820/135966950-f5264388-43a8-4544-9cc0-075458961dba.png)

**Comment by AdamSturge** [comment]
I just checked again and yeah I found it. You can close this bug
