### ISSUE TITLE
[FEATURE] Change the Wild Surge message so it rolls a d100 out of a rolltable

### ISSUE THREAD

**Issue by Eyescar** [johnnolan/wild-magic-surge-5e#441]
**Describe the new feature**
Should be similar to when you're using  the Auto Roll Table, but adding the possibility to the player rolling the d100 and then it returns the roll AND the rolltable result, instead of either automating every step or manually consulting the table after the raw roll

**Expected behavior**
1)Wild Magic Surge occurs
2)Player clicks on the message to roll a d100.
3)System rolls the dice and shows in chat the roll AND what happens considering the rolltable.

**Additional Information**
Please add any additional information or context.

**Comment by johnnolan** [comment]
## Notes

- Look at creating a custom chat card layout to have buttons and manage steps
- Tidy up settings so the right configuration is easier to setup
- Add a button to the chat card to manually click to roll d100/table and display result
- Should this all happen on one card or mutliple?
- Think about automation vs part automation vs no automation

**Comment by johnnolan** [comment]
@Eyescar going to merge this tomorrow but I have now added a new option on the Auto Roll Table option to select that a player must click the button in the chat message that indicates a surge has happened. When clicked it will roll the surge table and display the result to the chat.

Hopefully that does what you wanted, shout if not and once released tomorrow let me know if something isn't right
