### ISSUE TITLE
[BUG] "Name of Wild Magic Surge feat" field not working

### ISSUE THREAD

**Issue by ZeroXNoxus** [johnnolan/wild-magic-surge-5e#446]
**Describe the bug**
(Custom) Wild Magic Surge feat name is ignored. Whenever a spell is cast, the Wild Magic Surge table is rolled, even though the character doesn't have a feat equal to the name provided in this field.

**What version of FoundryVTT are you using?**
[Foundry VTT] 0.10.291

**To Reproduce**
1. Go to 'Wild Magic Surge 5e' module settings
2. Set a (custom) 'name of Wild Magic Surge feat' (mine is 'Unstable Focus')
3. Toggle 'Automated Wild Magic Surge' to on
4. Toggle 'Whisper Wild Magic Surge Roll Check to GM' to on
5. Set 'Wild Magic Roll Feature' to 'Spell Level Dependent Rolls'
6. Customize settings in 'Spell Level Dependent Rolls Variant'
7. Set 'Auto Roll Table' to 'Auto Roll Table'
8. Set a custom 'Roll Table Name'

**Expected behavior**
I'm now expecting that only characters with a feature called 'Unstable Focus' will automatically roll on the Magic Surge table.

**Screenshots**
Correct behaviour:
![image](https://user-images.githubusercontent.com/29397572/210290951-855effe2-bafa-462c-b5a1-c77901487cf3.png)
Incorrect behaviour:
![image](https://user-images.githubusercontent.com/29397572/210291036-f8c9e841-59ee-470d-a126-b735c9f5bc95.png)
Settings:
![image](https://user-images.githubusercontent.com/29397572/210291077-949e2120-af4e-479b-8fb7-7b58f3824967.png)
![image](https://user-images.githubusercontent.com/29397572/210291112-bccae7dc-cbe0-4fa0-b89f-17a6f32cc02f.png)

**Comment by johnnolan** [comment]
Hi, thanks for the report, I think this may have to do with the setup of the Feature.

You currently have Unstable Focus setup as a `Passive Ability` rather than a `Active Abilitiy`. This means there is no resource to track and the module will presume that Unstable Focus has always been used and will auto surge on every spell.

Can you change the feature to be like the following image and try again? I have also attached an example Feature you can import and rename.

![image](https://user-images.githubusercontent.com/5390820/210316288-0b6b017f-779b-4585-9d1a-6d99b1503692.png)

[fvtt-Item-tides-of-chaos.zip](https://github.com/johnnolan/wild-magic-surge-5e/files/10334891/fvtt-Item-tides-of-chaos.zip)

**Comment by ZeroXNoxus** [comment]
Hi @johnnolan, first of all, I've just setup the feature as you've described and the problem that every spell cast still exists.

Just to clerify, I've tried to set it up like this:
Ikarus (the Wild Magic Spellcaster) has the feature "Unstable Focus", which should be checked by the module to be necessary to active the automatic roll on the Wild Magic Surge Table (as I've understood the purpose of this module to automate the Wild Magic Surge)
Sylvie, the normal spellcaster without the feature, should not activate the Wild Magic Surge Table roll because she is lacking the "Unstable Focus" feature.

Am I using the module in an unintended way? Or may this be a bug with a different name in the "Name of the Wild Magic Surge feat" field?

**Comment by johnnolan** [comment]
Wow, that is really strange, okay, let me see if I can replicate this my end and dig deeper, sorry about this!

Could you send me the following please and I can set it up here

1. Right click on the Ikarus and the Sylvie actors and choose export data for each. That should give you two json files that you can attach on this ticket
2. Right click the Unstable Focus feature in the Items list and export data and send that over as well
3. You may have to add all 3 to a zip file to attach to the ticket

That should give you 3 json files that I can then import here and check what is happening and fix as needed

![image](https://user-images.githubusercontent.com/5390820/210354711-fb7545fb-454a-4d09-af44-e456784d02aa.png)
![image](https://user-images.githubusercontent.com/5390820/210354781-dc45d2cd-4051-4f20-93d2-8db42334b575.png)

**Comment by ZeroXNoxus** [comment]
No worries, my use-case is not the most common one as we do have a very special application for our homebrew Wild Magic Surge. Here you go:
[Exported Characters & Features.zip](https://github.com/johnnolan/wild-magic-surge-5e/files/10336540/Exported.Characters.Features.zip)
I've also taken the liberty to send you the used Wild Magic Surge table as well:
[Wild Magic Table.zip](https://github.com/johnnolan/wild-magic-surge-5e/files/10336553/Wild.Magic.Table.zip)

If you require any additional information, feel free to ask me, I'll provide as much information as you require.

Thank you for looking into this issue!

**Comment by ZeroXNoxus** [comment]
Maybe this can be helpful: If you have the [Forien's Copy Environment](https://foundryvtt.com/packages/forien-copy-environment) Module installed and activated, you can import my settings for the "Wild Magic Surge 5e" module, as well. I've provided them in the attached .zip file

![image](https://user-images.githubusercontent.com/29397572/210359585-85bdbc64-4c64-4172-81f4-0340ac31d1ac.png)
[Module Settings.zip](https://github.com/johnnolan/wild-magic-surge-5e/files/10336645/Module.Settings.zip)

**Comment by johnnolan** [comment]
Excellent, I found the issue thanks to the settings you shared! Checking locally this fix now

For Ikarus, it will not check for a surge on any spells ending in `(R)`. It will check for all other spells
Sylvie and any other character that has a spell will be ignored unless they have the Unstable Focus feat

This ended up being a bug in the Regex option that meant any spell any character cast would trigger :( Should be released soon for you

**Comment by johnnolan** [comment]
Released now and should be available https://github.com/johnnolan/wild-magic-surge-5e/releases/tag/3.13.2 let me know if it doesn't fix it though and we can reopen this ticket
