### ISSUE TITLE
Critical Miss (Fumble)

### ISSUE THREAD

**Issue by Vesselchuck** [johnnolan/wild-magic-surge-5e#45]
**Describe the new feature**
The option to automatically roll on a custom RollTable for any critical miss (Natural 1) made by PC or NPCs for the attack roll. 

**Expected behaviour**
When a certain actor gets a critical miss (Natural 1) on a d20 when rolling for the attack (should work with midi-qol merged card), it should trigger a roll on a Fumble RollTable by itself or maybe ask a player to roll via dialogue window.

**Additional Information**
I mostly want to use the Fumble RollTable from this book (pg. 49):
https://www.dmsguild.com/product/228484/Xanathars-Lost-Notes-to-Everything-Else
It would be really convenient this module could automate the rolling process, or at least bring up the dialogue window to click “Roll” button.

**Comment by johnnolan** [comment]
Hi, thanks for the suggestion. I could definitely make this work, however to keep it within the bounds of the module it would be an optional feature that would still rely on the PC having the Wild Magic Surge feat. 

Would that still work for you or are you after any player rolling a Nat 1?

**Comment by Vesselchuck** [comment]
If this is the only way to add this kind of functionality to the module, it's obviously better than constantly making throws manually, so I'm all for it.
