### ISSUE TITLE
Player Trigger Roll doesn't work; only GM is sent surge announcement

### ISSUE THREAD

**Issue by Jefferydo** [johnnolan/wild-magic-surge-5e#482]
With only WMS and DF Manual Rolls running, the "Player Trigger Roll" option of the "Auto Roll Table" feature doesn't work with the configuration below. The GM receives the surge announcement and button, the player receives a notice of a private GM roll.

The workaround is for the GM to right-click the roll message and share with players.

Foundry v 10.291

**To Reproduce**
Configure as per the screen shots.

**Expected behavior**
The player receives the chat notice with a button to roll on the surge table.

**Screenshots**
![2023-02-20-Wild-Magic-Surge-bug-result](https://user-images.githubusercontent.com/11779859/220181035-f4fda166-2936-4d00-81bc-3710eb93f0d1.png)

![2023-02-20-Wild-Magic-Surge-bug](https://user-images.githubusercontent.com/11779859/220181056-27f7623b-c4d7-4edd-865e-07e9345a4663.png)

**Comment by johnnolan** [comment]
Thanks for raising the issue, I have changed the logic now so if the GM has private or blind rolls selected the message will override this and show as public unless you specifically choose to whisper rolls in settings.
