### ISSUE TITLE
Problems when Automate Wild Magic Surge is disabled

### ISSUE THREAD

**Issue by Jefferydo** [johnnolan/wild-magic-surge-5e#484]
With "Automate Wild Magic Surge" disabled and the rest of the configuration below, 
- the surge count doesn't increase
- using DF Manual Rolls (value of 1) doesn't trigger a surge.

![2023-02-20-df-manual-rolls](https://user-images.githubusercontent.com/11779859/220183234-e051ca99-027b-4666-b665-94199f9b545b.png)

- the player never surges with "Automate Wild Magic Surge" disabled. It's not clear how this is supposed to behave from the instructions:

![2023-02-20-automate-wms](https://user-images.githubusercontent.com/11779859/220182905-ae29e49b-449c-473d-8f2a-e49d7e39f4ea.png)

![2023-02-20-chat-option](https://user-images.githubusercontent.com/11779859/220183040-4614e6f8-a7c8-4e5f-a3e6-27109851b736.png)

Foundry v 10.291

**To Reproduce**
Configure as per the screen shots.

**Expected behavior**
Surge count increases
WMS returns the results of the wild magic check
WMS recognizes DF Manual Roll result 
Re-write clear instructions. Consider recommending settings in the readme for common Scenarios A, B and C.

**Screenshots**
As below, except that "Automate Wild Magic Surge" is disabled.

![2023-02-20-Wild-Magic-Surge-bug](https://user-images.githubusercontent.com/11779859/220184674-4b1a382a-eb25-44db-aa85-609109be32c9.png)

**Comment by johnnolan** [comment]
Hi, thanks for this, I am going to rewrite the instructions for this setting this week. In the mean time I will try and explain a little better.

Having `Automate Wild Magic Surge` unchecked will just show a message in chat reminding you to roll for a Wild Magic Surge. All other funtionality will not work including incrementing counts.

I do have some videos that go over the settings but they might not be clear enough as well or the right format for you to get the information you need.

I will update the description and name of the setting to make it more clear and reply in more detail on your scenario soon, hope that helps for now.

**Comment by Jefferydo** [comment]
Ah, thanks. I assumed the trigger check was core.
