### ISSUE TITLE
[FEATURE] Add filter to only roll for Wild Surge if a sorcerer spell was cast

### ISSUE THREAD

**Issue by gh7531** [johnnolan/wild-magic-surge-5e#55]
**Describe the new feature**
Adding some sort of filter to allow to differentiate between sorcerer spells and non sorcerer spells for multi-classed characters. 
Since multi-classed characters may have non sorcerer spells, the automatic roll for the Wild Surge should only be done if a sorcerer spell is cast.

**Expected behavior**
If "Automate Wild Magic Surge" is checked and a spell somehow classified as a sorcerer spell is cast, automatically roll a d20 for the Wild Surge. If the spell is _not_ classified as a sorcerer spell don't roll the d20 for the Wild Surge.

**Additional Information**
AFAIK there is currently no field in a spell item that contains from which class a spell originates. There is [a open issue in the 5e core system repo, requesting this feature](https://gitlab.com/foundrynet/dnd5e/-/issues/1351). It seems like the currently used way of distinguishing spells would be to change the spell name for the character, e.g  'Magic  Missile' would be 'Magic Missile (S)' if the spell originates from the sorcerer class.
I [forked your repo and hacked together a basic version of the feature I'm requesting](https://github.com/gh7531/wild-magic-surge-5e). I'm using a RegEx to check if the name of the cast spell matches a string provided in the module settings.
![Peek 2022-01-08 00-26](https://user-images.githubusercontent.com/9028609/148619981-0dc3ef5f-df64-4d98-887b-88fc79831515.gif)
I can create a PR if you are interested in implementing this feature in your module.

**Comment by johnnolan** [comment]
Hi, thanks for the request! Will get on it this week and take a look at your solution to it. Going down the regex route is a good option, going to have a think of any other things that I may be able to tap into and will get back to you!

**Comment by johnnolan** [comment]
I have dug around and am coming to the same conclusion as yourself. Could you raise a PR from your repo to this one, we can then work together to finalise a few things and I can add some tests in after its merged.

Especially want you to have your name against the codebase as you have put a lot of effort into the code, if you have time

**Comment by gh7531** [comment]
Hi, happy to help out. 
I opened a PR and I should have some spare time tomorrow and in the next week and would be happy to work with you on this :+1:

**Comment by johnnolan** [comment]
Thanks again, that is now live, any issues then let me know in a new issue and I will jump on it for you!
