### ISSUE TITLE
[BUG] This module needs to be updated for changes to resource consumption

### ISSUE THREAD

**Issue by MotoMoto1234** [johnnolan/wild-magic-surge-5e#631]
**Describe the bug**
In 2.4 dnd5e the entire automation related to tides of chaos is dead.  My guess the changes to resource consumption has broken the module.  Tides doesn't recharge, tides doesn't cause a surge

**Actor Export**
To help with debugging, please export your actor data and attach the file to this ticket.

**To Reproduce**
1. It happens with a starter hero in 2.4 dnd5e, other modules also needed to adjust to the changes to resource consumption.  

**Expected behavior**
When tides of chaos is 0/1, it should auto surge on a leveled spell cast and then refill the resource.  

**Screenshots**
![image](https://github.com/johnnolan/wild-magic-surge-5e/assets/116308065/296e2965-8513-419e-8ea6-b8636ae39409)

**Comment by johnnolan** [comment]
Cheers for the report, haven't looked at the new version yet, will see what I can do this week to sort it

**Comment by MotoMoto1234** [comment]
With you not seeing it, I decided to go back and look and it seems that the resources all get jumbled when you update to 2.4, which then confuses link item resource module.  I had a tides of chaos in resource 1 instead of 3.

**Comment by MotoMoto1234** [comment]
Yeah I spoke too soon its borked stil with the wrench setting saying everything is fine with wildmagic surge

**Comment by MotoMoto1234** [comment]
Ok I have nailed down what happened.  When you migrate existing actors to 2.4+ dnd5e, the charges get cleared(either a module interaction or the migration script itself) and when this happens, if tides of chaos had 0 of 1 charges, cause of live play and the player having it expended while I was updating dnd5e, the migration for some reason turns 0's to blank/null.  And while its in this initial state, your module does not even know tides of chaos exists, once I performed a simple item update on the item sheet, suddenly it started working again.  And it didn't break at all ever after fiddling, something about that initial state after migration.  I think the values go blank because of link item resource module being active during the migration.  Cause I know resources when at 0 are null.  Never seen features/item uses having that behavior till now.  Either way its fixed, the item just needed to be nudged with an item update.

**Comment by johnnolan** [comment]
OMG what a edge case and well done for finding that out! I am going to look in the future at auto setting up a character with these things and will include this check in the setup/repair. Thanks so much for persisting and sharing the fix. I will make sure this is visible for anyone else who may encounter it.

**Comment by MotoMoto1234** [comment]
I have actually discovered more about this issue.  If a wild magic sorcerer has link item resource module managing their feature/resource for tides of chaos.  If they manually delete the value in the resource without typing an actual `0` in its place, the feature gains a `null` and wild magic surge 5e fails to recognize tides of chaos till someone populates a 0 or a 1 in the feature.  I dunno who needs to fix what, and this is an edge case, but I discovered it atleast.  I checked to make sure any module interactions weren't causing the resource to update to null, it seems to be only possible if a user just simply selects the 1 in the value field on the resource and deletes it(it then auto populates a faux zero that then transfers a null to the feature via link item resource).  Its easily reproduced.

**Comment by MotoMoto1234** [comment]
[Link item resource and WMS.webm](https://github.com/johnnolan/wild-magic-surge-5e/assets/116308065/6e4ee9fd-4eab-4e9a-ba54-e55b498256f7)
Here is the clip of the issue that breaks tides of chaos.  Mrprimate said that this kinda needs WMS to account for null maybe or possibly core needs to not do this with resources.

**Comment by Cobalt95240** [comment]
Hello,
any news for this bug since the last updates of Foundry and DnD module ? I still can't use it because of the ressources. Thank you

**Comment by MotoMoto1234** [comment]
Enable a legacy sheet and add it as a resource.  Also thats not related to this bug at all.  Thats just cause dnd5e decided to abandon resources altogether but you can still enable them via the legacy sheet or tidy5e.
