### ISSUE TITLE
[FEATURE] Barbarian - Pact of Wild Magic - Tasha's Cauldron of Everything

### ISSUE THREAD

**Issue by hallem** [johnnolan/wild-magic-surge-5e#67]
**Describe the new feature**
_Tasha's Cauldron of Everything_ added a Primal Path for the Barbarian class called _Path of Wild Magic_. At 3rd level the PC gains a _Path of Wild Magic_ feature that causes a roll against a shorter table whenever Rage is used.

**Expected behavior**
It would be great to have this new Pact of the Wild Magic included in this module.

**Additional Information**
The source content and roll table can be found in Tasha's Cauldron of Everything.

**Comment by johnnolan** [comment]
Note for myself

Source: https://www.dndbeyond.com/sources/tcoe/barbarian#PathofWildMagic

Given I am a `Barbarian`
And I have the feat `Path of Wild Magic`
When I cast `Rage`
I roll on a Custom Wild Magic Table

Requirements

* Add additional options menu
* Set custom Wild Magic Table for this feat
* Add a check like Sorcerer for the above configuration
