### ISSUE TITLE
[FEATURE] Auto surge when Tides of Chaos expired

### ISSUE THREAD

**Issue by LukasPrism** [johnnolan/wild-magic-surge-5e#75]
Please consider adding a surge reminder/button in chat or automatic surge roll when the sorcerer casts a leveled spell and their Tides of Chaos is used, per this rule:

“Before you regain use of this feature, the DM can have you roll on the Wild Magic Surge table after you cast a 1st level or higher spell. You then regain the use of this feature.”

This would help players and DMs remember to roll more surges and facilitate the Tides of Chaos recharge. 

Many thanks for an outstanding module!

**Comment by johnnolan** [comment]
@LukasPrism Just rereading this and wanted to confirm before I go too far! Does this scenario do what you want?

Given I have cast a spell at Level 1 or higher
And I **have** used Tides of Chaos
It **should** roll on the Wild Magic Table
It **should not** roll for a surge check
It **should** reset Tides of Chaos

Given I have cast a spell at Level 1 or higher
And I **have not** used Tides of Chaos
It **should not** roll on the Wild Magic Table
It **should** roll to check for a surge

**Comment by johnnolan** [comment]
Right I think that is it, releasing now. Its a opt in thing in the settings as I don't want to enable it and effect current setup of the module for others.

Let me know if I get any of this wrong or it doesn't work and I will get it sorted.

Thanks again for reaching out, love you are enjoying it!
