### ISSUE TITLE
Restore Tides of Chaos after Wild Magic use

### ISSUE THREAD

**Issue by flamewave000** [johnnolan/wild-magic-surge-5e#9]
Any time a Wild Magic surge occurs, it will automatically restore your Tides of Chaos ability. I don't know if there is a "uses" on the feat or if it is just tracked using Resources, but it should be reset after a surge occurs.

PHB 103: Tides of Chaos, Paragraph 2

**Comment by johnnolan** [comment]
> 
> 
> Any time a Wild Magic surge occurs, it will automatically restore your Tides of Chaos ability. I don't know if there is a "uses" on the feat or if it is just tracked using Resources, but it should be reset after a surge occurs.
> 
> PHB 103: Tides of Chaos, Paragraph 2

Hi, I have a new beta release available that I will merge tomorrow but in the mean time, if you have the availability, you can install and test if you like from the following link https://github.com/johnnolan/wild-magic-surge-5e/releases/download/0.4.0-beta/module.json

Thanks again and no problem if not, just wanted to give you the option ahead of release
John
